### ISSUE TITLE
Data synchronization rate consulting

### ISSUE THREAD

**Issue by 1620404793** [onozaty/postgresql-copy-helper#1]
Hello, I would like to ask if you use the pg copy method, is it faster to copy the file directly or to use the way you convert to csv stream. Or I can batch generate large csv files and copy them quickly.
The next is to copy the file stream directly
<img width="488" alt="32ed3c8a40e46a4659c48a02c91daa0" src="https://github.com/user-attachments/assets/5702e87d-685d-4021-81f9-7fa53b90a951">

**Comment by onozaty** [comment]
> The next is to copy the file stream directly

This is probably the fastest way.

Thanks.

**Comment by 1620404793** [comment]
Ok, thanks
